FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app app
COPY src src
COPY .streamlit .streamlit

CMD ["python", "-m", "streamlit", "run", "app/frontend/streamlit_app.py", "--server.address=0.0.0.0"]
